### ISSUE TITLE
Test data not available to the public

### ISSUE THREAD

**Issue by pgarrison** [bioio-devs/bioio-ome-zarr#14] opened 2024-04-12 18:20 UTC
The test data for `test_reader.py` is not publicly available, so users outside our organization cannot run the tests.

I also don't have authorization.

**Comment by SeanLeRoy** [comment] 2024-09-24 18:19
Duplicate of this one, but for another repo
https://github.com/bioio-devs/bioio-tifffile/issues/16

**Comment by BrianWhitneyAI** [comment] 2024-12-19 00:13
Going to close this since its a duplicate

**Closed by BrianWhitneyAI** 2024-12-19 00:13 UTC
Labels: bug
